analyzer:
  errors:
    missing_required_param: ignore
    missing_return: ignore
    invalid_override: ignore
    unused_import: warning
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false